### ISSUE TITLE
How to see reserved domains data?

### ISSUE THREAD

**Issue by ridvankaradag** [Oleg-Arkhipov/whois#8]
Hi, normally unregistered domain like this;
![not-found](https://user-images.githubusercontent.com/22245039/34109534-ef0eb6e6-e414-11e7-93c0-6503ec2d200b.PNG)
but some of domains may reserved like this;
![reserved](https://user-images.githubusercontent.com/22245039/34109550-feabe524-e414-11e7-976a-ad56695c125d.PNG)
How can i see this information with your code?
Thanks.

**Comment by Oleg-Arkhipov** [comment]
@ridvankaradag I am sorry for the late reply. Could you, please, provide me with example of both types of domains?

**Comment by ridvankaradag** [comment]
Thanks for reply. You can see https://www.whois.com/whois/1453.ist
